### ISSUE TITLE
Symfony3 has added workflow feature, will this conflict  with BMP?  

### ISSUE THREAD

**Issue by videni** [phpmentors-jp/workflower#32]
maybe this library can try to  integrate with Symfony's workflow,   so we don't use two solutions to solve the same problem.

**Comment by iteman** [comment]
The Symfony Workflow Component looks like a state machine library for general purpose, not for a BPM software that uses BPMN 2.0. It  could be used instead of our state machine library [Stagehand_FSM](https://github.com/phpmentors-jp/stagehand-fsm) that is only used as a mechanism behind the Workflow model.

I believe that these will solve different problems so these will not conflict.

**Comment by videni** [comment]
@iteman  , thanks , good to know.
